[package]
name = "linear-regression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = "3.2.1"
actix-web = "4.1.0"
lazy_static = "1.4.0"
serde = "1.0.143"
